config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root 'users#show'

  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user
  get 'users/:id' => 'users#show', as: :user

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

  get 'vacations/new' => 'vacations#new', as: :new_vacation
  get 'vacations/:id' => 'vacations#show', as: :vacation
  post 'vacations' => 'vacations#create', as: :create_vacation
  delete 'vacations/:id' => 'vacations#delete', as: :delete_vacation

  delete 'photos/:vacation_id' => 'photos#delete', as: :delete_photo
  get 'photos/vacation/:vacation_id/new' => 'photos#new', as: :new_vacation_photos
  get 'photos/vacation/:vacation_id' => 'photos#show', as: :vacation_photos
  get 'photos/:id/edit' => 'photos#edit', as: :edit_vacation_photos
  patch 'photos/:id' => 'photos#update', as: :update_vacation_photos
  post 'photos/vacation/:vacation_id/new' => 'photos#create', as: :create_vacation_photos

  get 'api/vacations' => 'api/vacations#index', as: :api_vacations
  get 'api/vacations/:id' => 'api/vacations#show', as: :api_vacation

  get 'api/users/:id' => 'api/users#show', as: :api_user_vacation
  get 'api/me/photos' => 'api/me#me', as: :api_me

  post '/api/users' => 'api/users#create'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :vacation
  attachment :photo,  content_type: ["image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :vacations
  has_many :photos, through: :vacations

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/controllers/api/me_controller.rb
class Api::MeController < ApplicationController
  before_action :doorkeeper_authorize!


  # GET /me.json
  def me
   @current_user = current_resource_owner
  end

  private

  # Find the user that owns the access token
  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController


  before_action except: [:create], :doorkeeper_authorize!

  protect_from_forgery with: :null_session


  def show
    @user = User.find_by id: params[:id]
  end

  def create
  @user = User.create
  @user.username = params[:user][:email]
  @user.password = params[:user][:password]
  if @user.save
    render :user
  else
    render json: @user.errors, status: 422
  end
end

def delete
  @user = User.find_by id: params[:id]
  @user.destroy
  head :ok
end


end

app/controllers/api/vacations_controller.rb
class Api::VacationsController < ApplicationController


  before_action :doorkeeper_authorize!

  protect_from_forgery with: :null_session


  def index
    @users = User.all
  end

  def show
    @vacation = Vacation.find_by id: params[:id]
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action do
  @current_user = User.find_by id: session[:user_id]
end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new
    @photo.vacation_id = params[:vacation_id]

    @photo.location = params[:photo][:location]
    @photo.user_id = @current_user.id

    response = Http.get("http://locationiq.org/v1/search.php?key=df45dfb24a963a502257&format=json&q=#{@photo.location}")
    results = JSON.parse(response.body)

    @photo.latitude = results.first["lat"]
    @photo.longitude = results.first["lon"]

    @photo.photo = params[:photo][:photo]

    if @photo.save
      redirect_to user_path(id: @current_user.id)
    else
      render :new
    end
  end

  def edit
    @vacation = Vacation.find_by id: params[:id]
    @photo = Photo.find_by id: params[:id]
  end

  def update
    @photo = Photo.find_by vacation_id: params[:vacation_id]
    @photo.location = params[:photo][:location]
    @photo.user_id = @current_user.id

    response = Http.get("http://locationiq.org/v1/search.php?key=df45dfb24a963a502257&format=json&q=#{@photo.location}")
    results = JSON.parse(response.body)

    @photo.latitude = results.first["lat"]
    @photo.longitude = results.first["lon"]
    @photo.photo = params[:photo][:photo]
    if @photo.save
      redirect_to user_path(id: @current_user.id)
  else
  render :edit
  end
  end








end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @photos = Photo.all
  end

  def create
    user = User.find_by email: params[:email]
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(id: user.id)
      else
        render:new
      end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Signed out."
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action except: [:new, :create] do
    if session[:user_id].nil?
      redirect_to sign_in_path, notice: "You must sign in!"
    end
  end

  def new
    @user = User.new
    @photos = Photo.all
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(id: @user.id)
    else
      render :new
    end
  end

  def show
    @vacation = Vacation.new
    @vacations = Vacation.where("user_id = ?", "#{@current_user.id}")
    @photos = Photo.where("user_id = ?", "#{@current_user.id}")

  end



end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  def new
    @vacation = Vacation.new
  end

  def show
    @vacation = Vacation.find_by id: params[:id]

  end

  def create
    @vacation = Vacation.new
    @vacation.user_id = @current_user.id
    @vacation.name = params[:vacation][:name]
    if @vacation.save
      redirect_to new_vacation_photos_path(vacation_id: @vacation.id)
    else
      render :new
    end
  end


  def delete
    @vacation = Vacation.find_by id: params[:id]
    Vacation.find(params[:id]).destroy
    redirect_to user_path(id: @current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vaction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

  <div id="fb-root"></div>


  <% if @current_user %>
    <%= link_to "Sign out", sign_in_path, method: :delete %>
    <%= link_to "Travel Profile", user_path(id: @current_user.id) %>
    <% else %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Sign in", sign_in_path %>

<% end %>



<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<%= form_for @photo, url: update_vacation_photos_path do |f| %>
<div class="">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>
<div class="">
  <%= f.label :photo %>
  <%= f.attachment_field :photo %>
</div>
<%= f.submit %>
<% end %>

app/views/photos/new.html.erb
<%= form_for @photo, url: create_vacation_photos_path do |f| %>
<div class="">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>
<div class="">
  <%= f.label :photo %>
  <%= f.attachment_field :photo %>
</div>

<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: create_user_path do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>
<div class="text-center">
    <h2>Places our users have been!</h2>
</div>
<div id="map"></div>
<script type="text/javascript">

    var mymap = L.map('map').setView([
        51.505, -0.09
    ], 2);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'greenup.0m0k3acb',
        accessToken: 'pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA'
    }).addTo(mymap);

    <% @photos.each do |photo| %>
    var circle = L.circle([
        <%= photo.latitude %>, <%= photo.longitude %>
    ], 500, {
        color: 'red',
        fillColor: '#f03',
        fillOpacity: 0.5
    }).addTo(mymap).bindPopup(' <%= photo.location %>');

    <% end %>
</script>

app/views/users/show.html.erb
<div class="col-sm-12">



    <div class="col-sm-4">
      <div class="well">
        <% @vacations.each do |vacation| %>
        <%= link_to vacation.name, vacation_path(id: vacation.id) %>
        (<%= link_to "Add Photo", new_vacation_photos_path(vacation_id: vacation.id) %>) (<%= link_to "Delete", delete_vacation_path(id: vacation.id), method: :delete %>)<br>
        <% end %><br><br>
        <%= link_to 'Add New Vacation', new_vacation_path, class: "btn btn-primary" %><br>
    </div>
    </div>
    <div class="col-sm-8">

        <div id="map"></div>

        <script type="text/javascript">

            var mymap = L.map('map').setView([
                51.505, -0.09
            ], 2);

            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                maxZoom: 18,
                id: 'greenup.0m0k3acb',
                accessToken: 'pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA'
            }).addTo(mymap);

            <% @photos.each do |photo| %>
            L.marker([<%= photo.latitude %>, <%= photo.longitude %>]).addTo(mymap).bindPopup(' <%= photo.location %>');
            <% end %>
        </script>

    </div>
</div>

app/views/vacations/new.html.erb
<%= form_for @vacation, url: create_vacation_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/vacations/show.html.erb
<br>
<div class="col-sm-12">
    <div class="col-sm-6">
        <h3><%= @vacation.name %>
            <small>(<%= link_to "Add Photo", new_vacation_photos_path(vacation_id: @vacation.id) %>)</small>
        </h3>

        <% @vacation.photos.each do |photo| %>
        <br>
        <%= photo.location %><br>
        <%= image_tag attachment_url(photo, :photo, :fill, 150, 150, format: "jpg") %><br>

        (<%= link_to "Edit", edit_vacation_photos_path(id: photo.id) %>)<br><br>
        <% end %>
    </div>
    <div class="col-sm-6">
        <div id="map"></div>
        <script type="text/javascript">
            var mymap = L.map('map').setView([
                <%= @vacation.photos.first.latitude %>, <%= @vacation.photos.first.longitude %>
            ], 13);

            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                maxZoom: 18,
                id: 'greenup.0m0k3acb',
                accessToken: 'pk.eyJ1IjoiZ3JlZW51cCIsImEiOiJjaXFudW4wNjcwMWQ1Zm9ubjQ0eHB6ejU5In0.8U3wnPsvgv9fAV4VnC2apA'
            }).addTo(mymap);

            <% @vacation.photos.each do |photo| %>
            L.marker([<%= photo.latitude %>, <%= photo.longitude %>]).addTo(mymap).bindPopup(' <%= photo.location %> ');
            <% end %>
        </script>
    </div>

</div>